### ISSUE TITLE
Unattributed allocations for simple types

### ISSUE THREAD

**Issue by ct1n** [cloudwego/goref#41]
**Describe the bug**

grf doesn't seem to attribute allocations to the right types. Some simple types with large allocations don't show up at all.

**To Reproduce**

```
package main

import (
	"fmt"
	"runtime"
)

type foo[T any] struct {
	id T
	buf []byte
}

func newfoo[T any](n int) *foo[T] {
	return &foo[T]{
		buf: make([]byte, n),
	}
}

type bar struct {
	buf []byte
}

func newbar(n int) *bar {
	return &bar{
		buf: make([]byte, n),
	}
}

func main() {
	f := newfoo[int](1<<18)
	b := newbar(1<<19)
	f2 := newfoo[int](1<<20)
	b2 := newbar(1<<21)
	for {
		runtime.Gosched()
		if runtime.NumCPU() == 0 {
			break
		}
	}
	fmt.Println("%v", f, b, f2, b2)
}
```

```
go build . && ./grftest &
grf attach $(pgrep grftest) && go tool pprof -http=:5080 ./grf.out
```

**Expected behavior**

Types `foo[int]` and `bar` should show up in the graph and should account for most of the space usage.

**Screenshots**

![Image](https://github.com/user-attachments/assets/e59675c7-3ea4-4b34-a30a-db9b483ced42)

**Goref version:**

goref v0.0.3

**Environment:**

```
AR='ar'
CC='gcc'
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_ENABLED='1'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
CXX='g++'
GCCGO='gccgo'
GO111MODULE=''
GOAMD64='v1'
GOARCH='amd64'
GOAUTH='netrc'
GOBIN=''
GOCACHE='/home/ctn/.cache/go-build'
GOCACHEPROG=''
GODEBUG=''
GOENV='/home/ctn/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFIPS140='off'
GOFLAGS=''
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build1035710056=/tmp/go-build -gno-record-gcc-switches'
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMOD='/dev/null'
GOMODCACHE='/home/ctn/go/pkg/mod'
GONOPROXY='github.com/MediaCreek'
GONOSUMDB='github.com/MediaCreek'
GOOS='linux'
GOPATH='/home/ctn/go'
GOPRIVATE='github.com/MediaCreek'
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/opt/go'
GOSUMDB='sum.golang.org'
GOTELEMETRY='local'
GOTELEMETRYDIR='/home/ctn/.config/go/telemetry'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/opt/go/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.24.1'
GOWORK=''
PKG_CONFIG='pkg-config'
```

**Additional context**

**Comment by jayantxie** [comment]
I have tried to use dlv to debug your test program, and it shows the stack variables of `main.main` as follows:

```
$ dlv core largealloc core.20250418
Type 'help' for list of commands.
(dlv) gr 1
Switched from 0 to 1 (thread 2200796)
(dlv) bt
0  0x0000000000473d68 in runtime.mcall
   at /usr/local/go/src/runtime/asm_amd64.s:458
1  0x000000000049a007 in runtime.Gosched
   at /usr/local/go/src/runtime/proc.go:367
2  0x000000000049a007 in main.main
   at /root/gopath/src/github.com/jayantxie/leetcode/largealloc/main.go:35
3  0x0000000000440beb in runtime.main
   at /usr/local/go/src/runtime/proc.go:284
4  0x0000000000475c21 in runtime.goexit
   at /usr/local/go/src/runtime/asm_amd64.s:1700
(dlv) frame 2
> runtime.mcall() /usr/local/go/src/runtime/asm_amd64.s:458 (PC: 0x473d68)
Warning: debugging optimized function
Frame 2: /root/gopath/src/github.com/jayantxie/leetcode/largealloc/main.go:35 (PC: 49a007)
(dlv) locals
f = (unreadable could not find loclist entry at 0x5a5c for address 0x473d68)
b = (unreadable could not find loclist entry at 0x5aa4 for address 0x473d68)
f2 = (unreadable could not find loclist entry at 0x5aec for address 0x473d68)
b2 = (unreadable could not find loclist entry at 0x5b34 for address 0x473d68)
(dlv) 
```

location list entry is a dwarf data structure, used to describe the storage location of variables or data in memory. The above phenomenon can be inferred that the variables of the main function are optimized by the Go compiler and the location information of the variables is deleted. In this case, goref cannot record the variable name, and it will fallback to recording the function name of the stack frame. So the expected display should be `main.main`, but the actual display is `runtime.mcall`, which is indeed a problem. I have already fixed it in the pull request https://github.com/cloudwego/goref/pull/42.

![Image](https://github.com/user-attachments/assets/802f2165-b185-4d67-8945-62b9ec2fa652)

**Comment by ct1n** [comment]
That's strange. In my case dlv shows the variables:
```
$ dlv version
Delve Debugger
Version: 1.24.0
Build: $Id: 2d55e4d30150e3fc68e64357e21293d7920fc1f1 $
$ dlv core grftest core.1436587
xcr0: 0x2ff xstate_bv: 0x2ff
xcr0: 0x2ff xstate_bv: 0x2ff
xcr0: 0x2ff xstate_bv: 0x2ff
xcr0: 0x2ff xstate_bv: 0x2ff
xcr0: 0x2ff xstate_bv: 0x2ff
xcr0: 0x2ff xstate_bv: 0x2ff
xcr0: 0x2ff xstate_bv: 0x2ff
Type 'help' for list of commands.
(dlv) gr 1
Switched from 0 to 1 (thread 1436587)
(dlv) bt
0  0x0000000000491c27 in runtime.NumCPU
   at /opt/go/src/runtime/debug.go:43
1  0x0000000000491c27 in main.main
   at ./main.go:36
2  0x00000000004392ab in runtime.main
   at /opt/go/src/runtime/proc.go:283
3  0x000000000046db61 in runtime.goexit
   at /opt/go/src/runtime/asm_amd64.s:1700
(dlv) f 2
Command failed: command not available
(dlv) frame 2
> main.main() /opt/go/src/runtime/debug.go:43 (PC: 0x491c27)
Warning: debugging optimized function
Frame 2: /opt/go/src/runtime/proc.go:283 (PC: 4392ab)
   278:                         panic("unreachable")
   279:                 }
   280:                 return
   281:         }
   282:         fn := main_main // make an indirect call, as the linker doesn't know the address of the main package when laying down
the runtime
=> 283:         fn()
   284:         if raceenabled {
   285:                 runExitHooks(0) // run hooks now, since racefini does not return
   286:                 racefini()
   287:         }
   288:
(dlv) frame 1
> main.main() /opt/go/src/runtime/debug.go:43 (PC: 0x491c27)
Warning: debugging optimized function
Frame 1: ./main.go:36 (PC: 491c27)
    31:         b := newbar(1<<19)
    32:         f2 := newfoo[int](1<<20)
    33:         b2 := newbar(1<<21)
    34:         for {
    35:                 runtime.Gosched()
=>  36:                 if runtime.NumCPU() == 0 {
    37:                         break
    38:                 }
    39:         }
    40:         fmt.Println("%v", f, b, f2, b2)
    41: }
(dlv) locals
f = (*main.foo[int])(0xc000072020)
b = (*main.bar)(0xc00000e018)
f2 = (*main.foo[int])(0xc000072040)
b2 = (*main.bar)(0xc00000e030)

```

**Comment by jayantxie** [comment]
The optimization strategies of the Go compiler may differ on different platforms (such as macOS and Linux), which may result in differences in the generated DWARF debug information.

If delve works fine in your new environment, I guess goref works fine too.

**Comment by ct1n** [comment]
Indeed, now grf works a little better. I don't know what I did differently. I might have added the `runtime.NumCPU` call because I suspected the compiler might be eliminating some instructions.
Though it still doesn't attribute the memory usage to the foo[int] and bar types:

![Image](https://github.com/user-attachments/assets/8abbc2b9-253d-492f-b45e-8a190a9df424)

**Comment by jayantxie** [comment]
grf only shows variable and field names, with their types. Here the foo[int] and bar types don't belong to these.

**Comment by ct1n** [comment]
In many instances I noticed it shows a type hierarchy, with allocations attributed to the type at every level, which is very useful. It just doesn't seem to do it all the time. Not sure I understand the model of what grf is supposed to show.

**Comment by jayantxie** [comment]
It will try to display as much variable and type information as possible, but the compile optimization does not allow this attempt to always succeed. In case of such problems, it will fallback to a scanning method similar to GC to ensure that no memory statistics are missed. The specific principle can be referred to the documentation in readme.
